### ISSUE TITLE
Analog multiplexer is used as a digital multiplexer

### ISSUE THREAD

**Issue by gillspice** [FirstBuild/DryAgeMeat#2]
Would be better of using a 2:1 digital mux or implementing with logic gates.  Could add to PsOC also.

**Comment by jhlink** [comment]
I'd rather avoid moving any resources to the PSOC. It's only purpose was to interpret the thermistor readings. Adding any other features to the PSOC will only cost more development time.

**Comment by 1btechtools** [comment]
➤ James commented:

Project utilizes PSoC. This is not an issue any more.
