### ISSUE TITLE
Neopixels add un-necessary complexity

### ISSUE THREAD

**Issue by gillspice** [FirstBuild/DryAgeMeat#3]
Individually addressable LEDs are not a requirement and increase complexity and real-time burden on the photon.

**Comment by jhlink** [comment]
I will consult with the dry ager team about this. Perhaps a single strip 5V white led strip (not individually addressable) would be a good alternative.

**Comment by 1btechtools** [comment]
➤ James commented:

Individually addressable LEDs are not required. 
Project opts for dimmable white LED strips. 

This has been noted in the Prototype 2 roadmap within the [wiki](https://github.com/FirstBuild/DryAgeMeat/wiki).
